### ISSUE TITLE
Failed to create moti-dotnecore-stack in project....

### ISSUE THREAD

**Issue by dcolebatch** [bcgov/schoolbus#336]
Hi team,

I noticed that the PDF service seems to be defined twice in the `-deployment-template.json` which leads to this error _"Failed to create moti-dotnecore-stack in project [Schoolbus]"_ when trying to start the application in OpenShift.

It appears that there should be two distinct services, but you're sharing the same env var here:

https://github.com/bcgov/schoolbus/blob/master/openshift/templates/schoolbus-deployment-template.json#L347  

and here:

https://github.com/bcgov/schoolbus/blob/master/openshift/templates/schoolbus-deployment-template.json#L479

Is this a typo?  What do you have in production?

I'm looking forward to contributing to this project from Ontario :)

**Comment by swcurran** [comment]
Hi @dcolebatch,

Yes - that's a typo.  The deployment template evolved offline after initial saving to the repo.  We were still working on best practices for managing artifacts exported from OpenShift for use as templates.  The task to be done to resolve this issue is to re-export the entities from our OpenShift instances and then revise the templates as appropriate.  Not sure when we'll get to that, but will try to do that when I have a bit of time.

Let us (or me) know if you have any other questions.

**Comment by dcolebatch** [comment]
Thanks @swcurran - I understand.

As an alternative, would you consider adding a simple `docker-compose` file to the repo, so the app can be stood up on a development machine with OpenShift being installed?
